### ISSUE TITLE
<class 'UnicodeDecodeError'> returned a result with an error set

### ISSUE THREAD

**Issue by qq774724635** [ArtifexSoftware/pdf2docx#144]
环境：python 3.7，pip 22.1.2，pdf2docx 0.5.4，PyMuPDF 1.20.0，python-docx 0.8.11

步骤代码：
![image](https://user-images.githubusercontent.com/87413355/175495224-6c612050-9486-4af5-b5b0-922dd136eb54.png)

报错情况：
![image](https://user-images.githubusercontent.com/87413355/175495789-2d82cd3b-ab65-4356-9472-7c75a638b14f.png)

**Comment by qq774724635** [comment]
再上传一部分截图吧
![image](https://user-images.githubusercontent.com/87413355/175496043-8e0c70a2-afb8-437f-ba15-bfc40dc6552d.png)

**Comment by qq774724635** [comment]
目前看来应该是pdf格式的问题，我的pdf格式为ASNI，转换成utf-8是可以的，但是转换为已经没有内容了

**Comment by qq774724635** [comment]
![image](https://user-images.githubusercontent.com/87413355/175499908-fffd07ab-96ca-441b-bd65-dcd8eb24a725.png)

**Comment by ranger2001** [comment]
遇到类似问题，是一个msoffice2007创建的pdf文件。

**Comment by dothinking** [comment]
> 遇到类似问题，是一个msoffice2007创建的pdf文件。

不知是否方便上传或者发我邮箱你的pdf以便查找原因？感谢。

**Comment by ddzzhen** [comment]
这个问题看起来与我的很相似，似乎是编码问题，无法执行`get_texttrace`函数
#155

**Comment by ranger2001** [comment]
> > 遇到类似问题，是一个msoffice2007创建的pdf文件。
> 
> 不知是否方便上传或者发我邮箱你的pdf以便查找原因？感谢。
刚看到，希望有帮助。
[2.PDF](https://github.com/dothinking/pdf2docx/files/9194691/2.PDF)

**Comment by dothinking** [comment]
@ranger2001 感谢提供测试文件。

可以确定是 `get_texttrace()` 的问题，这是上游处理PDF的库 `PyMuPDF` 提供的方法，而它又是对上上游`MuPDF`相应函数的封装。彻底解决这个问题只有等他们官方修复，周期会比较长。

临时地，可以采用`try-except`的方式忽略这个错误。例如，找到 `RawPageFitz.py` 第70行（...\site-packages\pdf2docx\page\RawPageFitz.py）：

```python
try:
    spans = self.page_engine.get_texttrace()
except SystemError:
    # logging.warning('Ignore hidden text checking due to UnicodeDecodeError in upstream library.')
    spans = []
```

**Comment by dothinking** [comment]
`pdf2docx`用`get_texttrace()` 来检测隐藏的文本，然后根据需要是否输出到转化后的docx。例如，一些扫描的PDF书籍尤其是年代较远的文献，在扫描的图片层后面隐藏着一个OCR的文本层，方便文字复制和搜索。此时，可以通过设置参数`ocr=0`或者`ocr=1`来选择只输出图片或者只输出文本到docx（避免图片和文本的重叠），参考 #132 。

综合来看，绝大多数情况下都不需要考虑隐藏文本的问题，并且`get_texttrace()` 仅仅是对某些中文字体可能有问题，因此以上临时修复适用于绝大多数情况。
