### ISSUE TITLE
index error: list index out of range

### ISSUE THREAD

**Issue by sy108** [ArtifexSoftware/pdf2docx#156]
index error: list index out of range
File "D:\Anaconda\lib\site-packages\pdf2docx\text\Textspan.py", line 130
self.chars[0].origin, # the bottom left point of the first character

ps:
<img width="599" alt="搜狗截图22年07月29日1440_1" src="https://user-images.githubusercontent.com/110220886/181698847-0d4cff1b-6d68-438b-859b-ced2b7f1db72.png">

when I modified the code, the program stopped “[2/4] Analyzing document...” and kept running ……
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...

**Comment by dothinking** [comment]
Could you please provide your pdf file for issue tracking? Thanks in advance.
