### ISSUE TITLE
Table structure parsing issue

### ISSUE THREAD

**Issue by Mr-wang2016** [ArtifexSoftware/pdf2docx#160]
感谢楼主提供这么好的工具！

使用中发现个小bug：

[[https://github.com/dothinking/pdf2docx/blob/master/pdf2docx/table/TableStructure.py](url)
](https://github.com/dothinking/pdf2docx/blob/313be6223798516a10ebf381de473b0be56953af/pdf2docx/table/TableStructure.py#L400-L407)

如果404行的for走不进去，那么cells为[[]]，后面的代码会bug：'list index out of range'

**Comment by dothinking** [comment]
感谢指出问题。

之前确实遇到表格解析失败（因此404行的for走不进去）的时候，出现'list index out of range'的问题。后续改进这一块的时候，我会再重新思考一下。如果你有什么好的建议，也欢迎提出。感谢。

**Comment by Mr-wang2016** [comment]
您好

是否有考虑利用机器学习模型来处理布局的解析或者还原。但可能需要一定人力标注数据。
另外如果可以，想了解您是否有继续维护或者重构的计划？


谢谢

**Comment by dothinking** [comment]
感谢回复，我尝试过机器学习做版面分析，可能深度不够，效果不太好。如果有效果好的模型，欢迎集成进来作为可选的解析方式。
