### ISSUE TITLE
换页问题

### ISSUE THREAD

**Issue by an1018** [ArtifexSoftware/pdf2docx#167]
hi，pdf2docx效果挺好，但有些存在换页，在您的基础上修改了代码，新打包了pdf2docx-0.0.0 whl包，并且集成在PaddleOCR项目中，PR如下：https://github.com/PaddlePaddle/PaddleOCR/pull/7907

**Comment by p208p2002** [comment]
由 @an1018 修復過後的安裝包可以從這邊下載，確實可以解決換頁問題。

The package modify by @an1018 fix the blank paragraph issue and work well. The package link is bellow.

https://paddleocr.bj.bcebos.com/whl/pdf2docx-0.0.0-py3-none-any.whl

**Comment by dothinking** [comment]
> hi，pdf2docx效果挺好，但有些存在换页，在您的基础上修改了代码，新打包了pdf2docx-0.0.0 whl包，并且集成在PaddleOCR项目中，PR如下：[PaddlePaddle/PaddleOCR#7907](https://github.com/PaddlePaddle/PaddleOCR/pull/7907)

感谢，同时感谢 @p208p2002 提取具体的修改内容。

从代码来看，是通过设置最小章节间距和段落行间距（11Pt）的方式节省了空间，弥补了渲染错误导致的多出的内容空间。这是一个很好的思路，调整局部间距不影响细节版式，但为本来没有换页问题的页面带来了副作用：原本准确的间距受到影响。另外，这个修复也没有彻底解决问题，例如对于原本间距已经很密且出现跨页问题的页面，11Pt的间距并不一定能节省出空间。

当然，从关注内容的角度，这个修复可以应对多数场景。
