### ISSUE TITLE
parse section

### ISSUE THREAD

**Issue by LIBIN-K** [ArtifexSoftware/pdf2docx#188]
In this project, the pasring section needs to split the blocks extracted by the Mupdf into line.
why not directly use the extraction result blocks of the mupdf to calculate the sections

**Comment by dothinking** [comment]
The blocks extracted by `PyMuPDF` might not represent the correct document layout, e.g., `lines` in different paragraphs might be regarded as a same `block` by `PyMuPDF`. So, `Line` is better to be a basic element.

Sorry for my late reply.
