### ISSUE TITLE
ocr部分推荐RapidOCR

### ISSUE THREAD

**Issue by SWHL** [ArtifexSoftware/pdf2docx#193]
- 感谢作者这个项目，很棒
- 我看ocr部分还未做，推荐[RapidOCR](https://github.com/RapidAI/RapidOCR)
- 我是RapidOCR项目维护者，希望可以合作一下

**Comment by dothinking** [comment]
感谢非常好的建议以及 #89 中的评论。

我之前计划在 `pdf2docx` 中支持图片/扫描格式pdf的转换，后面考虑到和当前路线的不同以及一些技术难点，最终妥协了—— `pdf2docx` 专注常规pdf的转换，新建一个项目专门处理图片或扫描格式pdf。

目前新项目还只是个想法。`RapidOCR` 解决了文本OCR提取和工程化部署的问题，是不可或缺的一环。期待多多交流和合作。


抱歉这么久才回复。

**Comment by dothinking** [comment]
暂时关闭issue，欢迎随时开启和继续交流。
