### ISSUE TITLE
脚注

### ISSUE THREAD

**Issue by liuwei92** [ArtifexSoftware/pdf2docx#200]
这个可以识别word中的脚注吗？

**Comment by h3clikejava** [comment]
不行，请问你有解决方案吗？

**Comment by liuwei92** [comment]
> 

使用win32com.client 中Footnotes 可以解决;

**Comment by dothinking** [comment]
> 这个可以识别word中的脚注吗？

这个库的目的不是识别Word中内容，而是试图分析pdf中的内容，然后转换为Word相应的元素。目前还不能识别脚注，因为PDF没有脚注的概念，从内容上判断也有一定难度。将来有时间会研究下这个问题。
