### ISSUE TITLE
pdf转word，换行出现空格的问题

### ISSUE THREAD

**Issue by great-wind** [ArtifexSoftware/pdf2docx#205]
使用pdf2docx对pdf文件进行转换，原pdf换行的地方，在word中有空格，这个问题有大佬解决么？求指教

**Comment by l00242672** [comment]
源码里面修改Lines.py中的
        def is_end_of_english_word(c):
            return c.isalpha() or (c and c in punc_ex_hyphen)
为
        def is_end_of_english_word(c):
            return c.encode().isalpha() or (c and c in punc_ex_hyphen)

**Comment by dothinking** [comment]
感谢 @l00242672 解答及 #240 的PR。

`isalpha()` 仅对拉丁字母有效，对于中文等其他字符，需要先 `encode()` 将字符转换为字节序列，然后再判断。
