### ISSUE TITLE
def _color_output(msg): return

### ISSUE THREAD

**Issue by kazuser** [ArtifexSoftware/pdf2docx#208]
`def _color_output(msg): return f'\033[1;36m{msg}\033[0m'`
Is [it](https://github.com/dothinking/pdf2docx/blob/master/pdf2docx/converter.py#L471) ok?

**Comment by dothinking** [comment]
It's OK. Just add some color effect to the output text. 

![image](https://github.com/ArtifexSoftware/pdf2docx/assets/13885442/40f8a0a1-beda-4584-83d1-205fa80b651d)
