### ISSUE TITLE
是否可以换用PaddleOCR作用文字识别的引擎

### ISSUE THREAD

**Issue by ericosmic** [ArtifexSoftware/pdf2docx#209]
目前的pymupdf作为后台引擎无法识别扫描pdf文件， 是否可以换用PaddleOCR作为文字识别引擎并且配合pymupdf的文字格式和排版信息复原docx文件。

**Comment by dothinking** [comment]
感谢建议。目前想法是这个库仅处理常规的pdf，以后重新开一个项目处理扫描或图片pdf。

主要是考虑两者处理方法还是很大不同，`pyMuPDF` 可以提取常规pdf的所有信息包文本（坐标，颜色等）、图片、字体（大小，粗细等）、形状等，而ocr扫描pdf得到文字只是信息非常有限的第一步。

**Comment by dothinking** [comment]
暂时关闭 issue，欢迎随时开启和继续交流。
