### ISSUE TITLE
pdf内容为表格时，转成docx文字和表格是分离的

### ISSUE THREAD

**Issue by WaldenWong** [ArtifexSoftware/pdf2docx#217]
你好 作者，我有一个存有表格的pdf，当使用如下代码转换后，表格和文本是分开的，会有很严重的错位。请问能有更好的办法，或者参数可以调试吗？非常感谢！
```python
    cv = Converter('test.pdf')
    cv.convert('out_file.docx', parse_stream_table=False)
    cv.close()
```
test.pdf
![test.pdf](https://github.com/dothinking/pdf2docx/assets/53803954/f8e863c1-d842-435b-bbef-7c8076e1eec2)

out_file.docx
![image](https://github.com/dothinking/pdf2docx/assets/53803954/7d20d0e8-8f7d-4e3f-a3e9-4347763a9d08)

**Comment by alexw994** [comment]
试试修改这两个参数
min_svg_gap_dx, 
min_svg_gap_dy

**Comment by WaldenWong** [comment]
谢谢大佬 @alxw994 ，完美解决!
```python
cv = Converter('test.pdf')
cv.convert(
    'test.docx',
    parse_stream_table=False,
    max_border_width=0.5,
    min_svg_gap_dx=16, 
    min_svg_gap_dy=0.5
)
cv.close()
```
