### ISSUE TITLE
 Encountered error while generating package metadata.

### ISSUE THREAD

**Issue by Ahmad-tayyab-1** [ArtifexSoftware/pdf2docx#230]
I am getting this error while trying to install this library

![error](https://github.com/dothinking/pdf2docx/assets/147137391/17de00f1-bddc-4be5-8644-6a7e6b4fbc56)
![error 2](https://github.com/dothinking/pdf2docx/assets/147137391/96d6c0a2-34ab-4f56-a747-f2c10ddd4383)

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dothinking** [comment]
What's your Python version?
How about installing the latest version? `pip install pdf2docx`
If same issue, can you install `PyMuPDF` seperately? `pip install pymupdf`
