### ISSUE TITLE
The version matching relationship between Python, pdf2docx, and python-docx

### ISSUE THREAD

**Issue by master-progr** [ArtifexSoftware/pdf2docx#234]
The version matching relationship between Python, pdf2docx, and python-docx

**Comment by master-progr** [comment]
Python  3.11.5
pdf2docx  0.5.6
python-docx  ？

**Comment by dreamingdeer** [comment]
python-docx 0.8.11

**Comment by dothinking** [comment]
> python-docx 0.8.11 1.0.0 broken fixed in 1.0.1 [python-openxml/python-docx@129dd83](https://github.com/python-openxml/python-docx/commit/129dd83f4aef7991a6d21da892f2b4aa2e55de34)

Thanks a lot for this right answer!!

The importing issue due to python-docx 1.0.0 will be fixed in pdf2docx v0.5.7 (coming soon).

**Comment by dothinking** [comment]
`v0.5.7` released.
