### ISSUE TITLE
cannot find builtin font with name xxx

### ISSUE THREAD

**Issue by lomoonmoonbird** [ArtifexSoftware/pdf2docx#235]
pdf with chinese and when convert to docx, error occurs:

[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
[ERROR] cannot find builtin font with name 'Arial'

any solution or parameter to ignore fonts?

**Comment by heweisheng** [comment]
我用了个蹩脚的方法，搜索本机的字体文件再尝试一次，通常这些缺失字体在本机都有
部分代码来着chatgpt 出问题不负责

具体修改pdf2docx/text/TextSpan.py
![image](https://github.com/dothinking/pdf2docx/assets/37769332/651c0153-b6b0-4716-b7ca-92a1ab488833)


from fontTools.ttLib import TTFont
import os

import platform

def get_windows_fonts_directory():
    import ctypes
    CSIDL_FONTS = 0x14
    path_buffer = ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)

    if ctypes.windll.shell32.SHGetFolderPathW(0, CSIDL_FONTS, 0, 0, path_buffer) == 0:
        return path_buffer.value
    else:
        return None


def find_font(font_name, font_style=None):
    found_fonts = []

    font_dir = "/path/to/your/fonts"  # 替换为实际的字体目录
    if platform.system().lower()=="windows":
        font_dir=get_windows_fonts_directory()
    elif platform.system().lower()=="linux":
        font_dir = "/usr/share/fonts"
    else :
        font_dir = "/Library/Fonts"

    for root, dirs, files in os.walk(font_dir):
        for file in files:
            if file.lower().endswith((".ttf", ".otf")):
                font_path = os.path.join(root, file)
                try:
                    font = TTFont(font_path)
                    family = font["name"].getName(1, 3, 1, 1033).toUnicode()
                    # 防止字体文件中没有包含风格信息的情况
                    try:
                        style = font["name"].getName(1, 3, 2, 1033).toUnicode()
                    except Exception as e:
                        style = None

                    if family.lower() == font_name.lower() and (font_style is None or style is not None and style.lower() == font_style.lower()):
                        found_fonts.append({
                            "family": family,
                            "style": style,
                            "path": font_path
                        })
                except Exception as e:
                    print(f"Error processing font {font_path}: {e}")

    return found_fonts

![image](https://github.com/dothinking/pdf2docx/assets/37769332/71a3ff37-5118-4c85-9571-face0bf5839b)

**Comment by ayang** [comment]
和pymupdf版本有关，降到1.21就可以了
It is related of the pymupdf version, just downgrade it to 1.21.

**Comment by lomoonmoonbird** [comment]
![image](https://github.com/dothinking/pdf2docx/assets/10216631/630a1f8a-88eb-4f3d-a1a7-f9d2b2ae1c89)
作者在这里加了这两行代码，如果找不到base font14，就去找Arial字体，但是包里面没有这个字体，而且也没有入口从电脑中加载，pymupdf有这个功能，但pdf2doc没有，所以会报错， 把这两行删掉就没问题了，这两行比较多余。

**Comment by lomoonmoonbird** [comment]
> 我用了个蹩脚的方法，搜索本机的字体文件再尝试一次，通常这些缺失字体在本机都有 部分代码来着chatgpt 出问题不负责
> 
> 具体修改pdf2docx/text/TextSpan.py ![image](https://private-user-images.githubusercontent.com/37769332/286252838-651c0153-b6b0-4716-b7ca-92a1ab488833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1NTgsIm5iZiI6MTcwMzEyNDI1OCwicGF0aCI6Ii8zNzc2OTMzMi8yODYyNTI4MzgtNjUxYzAxNTMtYjZiMC00NzE2LWI3Y2EtOTJhMWFiNDg4ODMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZDllZWM0NzRkN2FjMmFkMWY1MGU0MjFmYmIxMTI3YmRiMGY1OWRkODZiOGIzNDQxMDg1YmNjY2I5YmVmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnrAREgTSHg7hAPAmpawn_iscrX97pOsVHPJE5Ld1Is)
> 
> ```
> from fontTools.ttLib import TTFont
> import os
> 
> import platform
> 
> def get_windows_fonts_directory():
>     import ctypes
>     CSIDL_FONTS = 0x14
>     path_buffer = ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)
> 
>     if ctypes.windll.shell32.SHGetFolderPathW(0, CSIDL_FONTS, 0, 0, path_buffer) == 0:
>         return path_buffer.value
>     else:
>         return None
> 
> 
> def find_font(font_name, font_style=None):
>     found_fonts = []
> 
>     font_dir = "/path/to/your/fonts"  # 替换为实际的字体目录
>     if platform.system().lower()=="windows":
>         font_dir=get_windows_fonts_directory()
>     elif platform.system().lower()=="linux":
>         font_dir = "/usr/share/fonts"
>     else :
>         font_dir = "/Library/Fonts"
> 
>     for root, dirs, files in os.walk(font_dir):
>         for file in files:
>             if file.lower().endswith((".ttf", ".otf")):
>                 font_path = os.path.join(root, file)
>                 try:
>                     font = TTFont(font_path)
>                     family = font["name"].getName(1, 3, 1, 1033).toUnicode()
>                     # 防止字体文件中没有包含风格信息的情况
>                     try:
>                         style = font["name"].getName(1, 3, 2, 1033).toUnicode()
>                     except Exception as e:
>                         style = None
> 
>                     if family.lower() == font_name.lower() and (font_style is None or style is not None and style.lower() == font_style.lower()):
>                         found_fonts.append({
>                             "family": family,
>                             "style": style,
>                             "path": font_path
>                         })
>                 except Exception as e:
>                     print(f"Error processing font {font_path}: {e}")
> 
>     return found_fonts
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/37769332/286252940-71a3ff37-5118-4c85-9571-face0bf5839b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1NTgsIm5iZiI6MTcwMzEyNDI1OCwicGF0aCI6Ii8zNzc2OTMzMi8yODYyNTI5NDAtNzFhM2ZmMzctNTExOC00Yzg1LTk1NzEtZmFjZTBiZjU4MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjM1ODY0YTdmN2M1NTJhMWZkZjQ5Mjc1YmRhYTEyOTFjODA1OTdjNGE0Y2FiYjkzOTBjYzJiYmQ1NmZlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.spzHs3mZTctzwhlJb3gAHkehflur5qMG0FzVM8-KIZw)

你这样的方式我也试过，这个情况是提前知道了你没有Arial字体报的错，然后再加入Arial字体，但之后朋友font1,font2,font3的时候就没法做到通用了

**Comment by dothinking** [comment]
感谢提交问题、分析和建议，问题根源确实如上图框出的两行代码。

那两行代码的目的是应对某些PDF缺失字体名称（unnamed font name），**且受影响文本的位置信息（bbox）不正确的场景**：利用一种PDF支持的默认字体来估算和修正受影响文本大致占据的位置。所以，删除两行确实可以应对绝大多数情况，但不是万全之策。更稳妥的方法是采用正真被所有PDF都支持的默认字体，例如PDF规范支持的14种基本字体中的`helv`。

具体参考 [#216](https://github.com/ArtifexSoftware/pdf2docx/issues/216#issuecomment-1875725823)

**Comment by dothinking** [comment]
新版本 `v0.5.7` 已解决此问题。

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
