### ISSUE TITLE
Inconsistent Table formatting while conversion

### ISSUE THREAD

**Issue by richa27gpt** [ArtifexSoftware/pdf2docx#238]
Dear Developer,
Thank you so much for developing such a cool and amazing library. It really is very helpful.
I am using this functionality as a part of my bigger project, and I have run into a roadblock. please help me with this as soon as you can, I'd really be grateful!

I am simply trying to convert one PDF to DOCX file, but while conversion there are a few miss with the table row color and some other formatting. I am attaching the sample PDF and generated DOCX file for your reference (I have filled some random data in the invoice file due to security issues, main concern is formatting).

I have tried Conversion and parsing, and changing many table_setting values. I still cannot get the same formatting in the generated DOCX file after conversion.

Looking forward for your swift response on this.
Thank you in advance!
<img width="523" alt="issues" src="https://github.com/dothinking/pdf2docx/assets/73694294/15e6af0b-91aa-458d-9ab6-022f23723202">
[Test.docx](https://github.com/dothinking/pdf2docx/files/13196745/Test.docx)
[Test.pdf](https://github.com/dothinking/pdf2docx/files/13196746/Test.pdf)

**Comment by richa27gpt** [comment]
Dear Developer @dothinking, please let me know if these conversion formatting issues can be fixed? 
If you need any other details, please feel free to ask. Looking forward for your response.
Thank you once again for your amazing library and work.

**Comment by nunamia** [comment]
I think Unable to resolve, only refactoring.

**Comment by greendreamer** [comment]
Hi @richa27gpt , same reason as #265
