### ISSUE TITLE
SOLUTIONS for cannot find builtin font with name xxxxx

### ISSUE THREAD

**Issue by lomoonmoonbird** [ArtifexSoftware/pdf2docx#241]
![image](https://github.com/dothinking/pdf2docx/assets/10216631/1e6c4a7f-67a9-4e50-b35f-eaa9e11b2d89)

this two line of code is unnecessary, this lib set Arial as default font, while you meet a unknow font or unresolved font when parsing a pdf, this code will be execute, but you dont have Arial font in your lib even you have in your system, pymupdf supports  load system font ,but this lib doesn't, and not only this Arial, but also other font you never meet before. so i removed this two lines code, everything is fine, the default font is utf-8, and you will not lose content when parsing a pdf.

**Comment by dothinking** [comment]
Thanks for your comments and suggestions.
The default font name is used when unnamed font is extracted with `pymupdf`, especially the layout/bounding box of affected text span is wrong, like [PyMuPDF#642](https://github.com/pymupdf/PyMuPDF/issues/642).
So, a better way is to set a real "default" font name, like `helv`, as explained here [#216](https://github.com/ArtifexSoftware/pdf2docx/issues/216#issuecomment-1875725823).
