### ISSUE TITLE
It can't parse border lines.

### ISSUE THREAD

**Issue by jjikkobro** [ArtifexSoftware/pdf2docx#244]
Hello, thank you for using these nice projects but I got an issue.
When I convert pdf to docx, It can not show me lines which are drawn by border-bottom in HTML.
Is there any way for it?

**Comment by dothinking** [comment]
Text underline feature should be supported by this library. Could you please share a test file for reproducing and debugging this issue? Thanks in advance.

**Comment by JorjMcKie** [comment]
Closed because of missing response for an extended period of time.
