### ISSUE TITLE
pdf转换成docx后，在一些电脑上显示的字体错误可能是什么原因呢

### ISSUE THREAD

**Issue by ericosmic** [ArtifexSoftware/pdf2docx#246]
同样的pdf文档， 在不同的电脑上转换后显示的字体不同。

但是在word上字体名称栏显示的字体都一样，但实际显示效果大相径庭。 这个问题能解决吗？
测试pdf：
[zf6.pdf](https://github.com/dothinking/pdf2docx/files/13775154/zf6.pdf)
在不同电脑上显示的效果
![Screenshot from 2023-12-27 11-33-55](https://github.com/dothinking/pdf2docx/assets/35327931/7aaa861e-495f-4f9d-8cbe-f2f0037a3a6b)

![98072031a80e91cd9f97d271e44f2f8b](https://github.com/dothinking/pdf2docx/assets/35327931/8846b463-39c4-40d1-8fbd-c7fc8aa0e340)

**Comment by dothinking** [comment]
感谢指出问题和提供案例。
直接原因是字体乱码，Word软件不得不采用某种默认字体来渲染，而不同电脑或Word软件的默认字体可能不同。
根本原因是 `pdf2docx` 的上游依赖库 `PyMuPDF` 提取的字体名称中带有乱码，而 `pdf2docx` 未能针对处理，参考 #194 。
问题可以解决，但是需要点时间（最近个人时间有限）。

**Comment by dothinking** [comment]
Fixed in version `v0.5.7`.

**Comment by Mr-wang2016** [comment]
您好
我参考了#194中的解决方案增加一行代码“basename = bytes(ord(c) for c in basename).decode()”后，运行后报错“UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 7: invalid start byte”。
所用的pdf为上文中的zf6.pdf
