### ISSUE TITLE
WARNING：Ignore Line "some text" due to overlap

### ISSUE THREAD

**Issue by sunny6chen** [ArtifexSoftware/pdf2docx#248]
Description:
I encountered a warning message: "WARNING: Ignore Line "some text" due to overlap" while using the application.

Question:
The warning indicates that certain text is being ignored due to overlap. I would like to understand more about the background of this issue and any potential solutions.

When working with complex PDFs, I encounter these warnings that result in the content being blank when saved to Word.

<img width="496" alt="image" src="https://github.com/ArtifexSoftware/pdf2docx/assets/29888472/fc023de4-2288-4739-a9bf-8dc04a9b97f5">

**Comment by dothinking** [comment]
Thanks for reporting this issue.

If your `PyMuPDF` version is upper than 1.23.11, please try this first: https://github.com/ArtifexSoftware/pdf2docx/issues/250#issuecomment-1890821033

If it does not work, may I have your pdf file for testing? Thanks.
