### ISSUE TITLE
所有文字丢失：Ignore Line xx due to overlap.

### ISSUE THREAD

**Issue by linjuchen** [ArtifexSoftware/pdf2docx#250]
如图，信息全部丢失。
![图片](https://github.com/ArtifexSoftware/pdf2docx/assets/33847736/51af403d-238f-422d-a61b-6535b47010bc)

**Comment by dothinking** [comment]
初步判断是上游库 `pymupdf` 升级导致的，请适当降低 `pymupdf` 的版本试试，例如，

```
pip install pymupdf==1.23.8
```

后续我会从 `pdf2docx` 的角度，检查和修复 `pymupdf` 升级带来的不兼容问题。

**Comment by itachi114514** [comment]
在运行时分别出现
>......lib\site-packages\pdf2docx\font\Fonts.py", line 72, in extract
    basename = bytes(ord(c) for c in basename).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 7: invalid continuation byte

和

>......\lib\site-packages\pdf2docx\text\TextSpan.py", line 59, in __init__
    self.font = bytes(ord(c) for c in font_name).decode() # in case unicode in font name
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte

在用try忽略错误后出现了如该issue所述相同的问题。
除此之外还产生了如下问题：
>[ERROR] Ignore page 44 due to parsing page error: 'TextSpan' object has no attribute 'line_height'

**Comment by dothinking** [comment]
@itachi114514 是否方便提供测试文件？谢谢。

`pymupdf`的版本？

**Comment by Chanwb** [comment]
> 初步判断是上游库 `pymupdf` 升级导致的，请适当降低 `pymupdf` 的版本试试，例如，
> 
> ```
> pip install pymupdf==1.23.8
> ```
> 
> 后续我会从 `pdf2docx` 的角度，检查和修复 `pymupdf` 升级带来的不兼容问题。

大佬怎么发现的 强

**Comment by itachi114514** [comment]
pymupdf的版本本来是最新版，后来依照issue中改成了1.23.8。附件是截取的测试文件。
________________________________

**Comment by dothinking** [comment]
@Chanwb 不敢当，我最近提交的更新通过了本地测试但是没通过在线测试，一看日志唯一区别是 `pymupdf` 的版本 🤣

**Comment by dothinking** [comment]
`v0.5.8` is released. All these issues should be fixed.

**Comment by CodesHour** [comment]
I am using pdf2docx 0.5.8 and pymupdf 1.25.5, but still those- "Igonore line due to overlap" is happening. The test pdf is a simple pdf with text and some simple tables.

"flask-babel>=4.0.0",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "pdf2image>=1.17.0",
    "pillow>=11.1.0",
    "psycopg2-binary>=2.9.10",
    "pymupdf>=1.25.5",
    "pypdf2>=3.0.1",
    "pytesseract>=0.3.13",
    "python-docx>=1.1.2",
    "werkzeug>=3.1.3",
    "pdf2docx>=0.5.8",
    "lxml>=5.3.1",
