### ISSUE TITLE
单元格内表格转换的文本错误

### ISSUE THREAD

**Issue by qktechies** [ArtifexSoftware/pdf2docx#262]
文件：
[demo.pdf](https://github.com/ArtifexSoftware/pdf2docx/files/14061009/demo.pdf)

转换成pdf后，整定项目和更改前列转换都有问题：
<img width="965" alt="企业微信截图_ca7c18f0-bab3-457e-82b0-f9d42936c4b4" src="https://github.com/ArtifexSoftware/pdf2docx/assets/5698952/da3f84d2-26f8-4a7a-bded-ef5f9ead712b">

**Comment by greendreamer** [comment]
Please check pdf2docx version. there isn't such issue in the latest version: v0.5.8.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
