### ISSUE TITLE
可不可以将pdf的字体自动添加到系统中以防止转换后乱码

### ISSUE THREAD

**Issue by gkngkngkn** [ArtifexSoftware/pdf2docx#270]
转了几个英文pdf出现乱码，原因是windows中缺少pdf里的英文字体,word里就显示乱码了，有没有办法将pdf中的字体自动添加到系统中？（pdf中的字体可以识别，在编辑软件里可以看到字体种类）

**Comment by greendreamer** [comment]
Hi @gkngkngkn , it is not good approach to implement adding fonts automatically, I think.
Feel free to open new issue and will consider `garbled characters` if you provide detailed description and examples.

**Comment by EvanSong77** [comment]
> 转了几个英文pdf出现乱码，原因是windows中缺少pdf里的英文字体,word里就显示乱码了，有没有办法将pdf中的字体自动添加到系统中？（pdf中的字体可以识别，在编辑软件里可以看到字体种类）

我也碰到了这个问题，有些英文pdf可以，但有些不行，请问你如何解决的
