### ISSUE TITLE
PDF转docx时文档中带链接的文字全部丢失

### ISSUE THREAD

**Issue by everydoc** [ArtifexSoftware/pdf2docx#272]
你好，我在Mac上通过pip安装了最新版，在用命令行将一个PDF文件转化成docx时，发现原来PDF中带链接的内容（文字、链接）全部丢失了，我不懂原因，所以冒昧来问一下是否是bug，还是我操作上有什么问题？
<img width="1469" alt="截屏2024-03-06 00 38 34" src="https://github.com/ArtifexSoftware/pdf2docx/assets/41568390/a11ff67a-a0ad-4823-a856-2a7cb3c99d03">

**Comment by nunamia** [comment]
建议你先提供下文件

**Comment by greendreamer** [comment]
Hi @everydoc , I have tried with some pdf files, but that is working correctly. Please provide example file.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
Feel free to open a new issue - however please with a reproducing example.
