### ISSUE TITLE
pdf2docx-0.5.8版,将附件"深入浅出强化学习01.pdf"转docx后,每段首句被移到末尾了

### ISSUE THREAD

**Issue by ericshenjs** [ArtifexSoftware/pdf2docx#273]
common\Collection.py文件sort_in_line_order函数中作如下修改可修复:
    # if not self.is_vertical_text:
    if self.is_vertical_text:

**Comment by ericshenjs** [comment]
[layout_修改前.json](https://github.com/ArtifexSoftware/pdf2docx/files/14519097/layout_.json)
[layout_修改后.json](https://github.com/ArtifexSoftware/pdf2docx/files/14519098/layout_.json)
源代码"if not self.is_vertical_text",debug后生成layout_修改前.json
源代码修改为"if self.is_vertical_text",debug后生成layout_修改后.json

**Comment by greendreamer** [comment]
Hi @ericshenjs , please provide example pdf for reproducing and doing better approach.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time. Feel free to open a new issue.
