### ISSUE TITLE
transfer error：unsupported colorspace for '{output}'

### ISSUE THREAD

**Issue by plainee** [ArtifexSoftware/pdf2docx#277]
the log is as below:

[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
unsupported colorspace for '{output}'

**Comment by Keguans** [comment]
It seems to be encountering a currently incompatible or unsupported colorspace in PDF. I also encountered this problem yesterday and I hope the author can pay attention to it.

**Comment by greendreamer** [comment]
Your image type contained in PDF may be invalid to support colorspace. For example, Colorspace is unsupported for JPEG.
Please provide sample pdf to dig deeper.

**Comment by greendreamer** [comment]
some logic has been implemented for pixmap in pdf2docx and updated in several versions. there may be some issues.
Please provide example pdf.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time. Feel free to open a new issue - however please with a reproducing example.
