### ISSUE TITLE
[WARNING] Ignore Line "<image>" due to overlap

### ISSUE THREAD

**Issue by GohanHango** [ArtifexSoftware/pdf2docx#278]
I'm getting an output that isn't accurate. Some images aren't on the same space as the original PDF.

Here is a sample:
Before:
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/89592598/ad05390c-3142-4046-9328-24d2b4955646)

After:
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/89592598/88675742-ebef-496a-88ad-5404d6ac7d4b)

There image multiplied by two. The first one being compressed and the second one being under the first image.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
Feel free to open a new issue - however please with a reproducing example.
