### ISSUE TITLE
转换时遇到字体名为中文（比如“宋体”）时，发生错误

### ISSUE THREAD

**Issue by hlhtddx** [ArtifexSoftware/pdf2docx#286]
如题，转换时遇到字体名为中文（比如“宋体”）时，发生错误
bytes must be in range[0  to 255]
错误点在
https://github.com/ArtifexSoftware/pdf2docx/blame/master/pdf2docx/common/share.py#L128
当字体名称为中文时，ord(c)大于255，转换成bytes时会报错
```python
def decode(s:str):
    '''Try to decode a unicode string.'''
    b = bytes(ord(c) for c in s) ### 这里出错
    for encoding in ['utf-8', 'gbk', 'gb2312', 'iso-8859-1']:
        try:
            res = b.decode(encoding)
            break
        except:
            continue
    return res
```

**Comment by hlhtddx** [comment]
缺了一遍，只有在选择multiprocessing=True才会出现问题，单进程模式不会出问题

**Comment by greendreamer** [comment]
Hi @hlhtddx , please provide songti font file for reproducing.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time. Feel free to open a new issue.

**Comment by RobertHoffman** [comment]
我也遇到了这个问题。
