### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by nic-Oban** [ArtifexSoftware/pdf2docx#287]
Hello,
is there any parameter to specify the langage of the original pdf to convert?
I mainly use french pdfs and accented character are displayed as 'e o 'u.
Thanks a lot for your help and have a good day

**Comment by greendreamer** [comment]
I am happy if you share your example pdf to reproduce.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
Feel free to open a new issue - however please with a reproducing example.
