### ISSUE TITLE
Table is broken when the table is displayed on 2 pages

### ISSUE THREAD

**Issue by pulse-mind** [ArtifexSoftware/pdf2docx#290]
Hello,

I am generating a PDF using wkhtml2pdf. In the PDF, the table is displayed on two pages because it is too big. When I convert this PDF into docx, the table is broken : 
A new table is added inside the row and it contains a part of the row.

![Feuille-de-presence__-__Mode_de_compatibilité](https://github.com/ArtifexSoftware/pdf2docx/assets/22203083/307f71ac-4d76-4071-8793-3616416e1a53)

I can share the PDF and the DOCX if necessary. Please let me know how to share...

Thanks a lot
Fred

**Comment by pulse-mind** [comment]
And my be if I can ask a another question here : The space between lines and between paragraph are bigger than on the PDF. How can I manage that ?

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
Feel free to open a new issue - however please with a reproducing example.
