### ISSUE TITLE
关于行高分配的逻辑疑问

### ISSUE THREAD

**Issue by heweisheng** [ArtifexSoftware/pdf2docx#291]
最近在做ocr还原扫描件（使用飞浆的面版识别+reportlib生成还原pdf），目前pdf排版比较方便，所以打算先转pdf在用pdf2docx(花时间写一套根据ocr实现排版感觉可以直接扩展这个项目，但是暂时还没有时间去扩展)
看了下pdf解析的时候可能存在多行一个段落的情况，但是多行的情况下行高应该要均分给每一行才对
会出现问题的具体情况：
[test_7.pdf](https://github.com/ArtifexSoftware/pdf2docx/files/15348474/test_7.pdf)

![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/c1471671-bbc5-42c7-9e72-28373dbfd9de)
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/1c6a1d20-a2d3-4799-80a3-f1ed064faeb3)
使用这个逻辑转换：
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/5684d2bf-80b6-4d14-9aaa-83ea78762f22)
均分行高：
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/82d2688e-5e8f-4563-b710-7c1d4c32816f)
另外可否中间插入空格行去做到排版尽量跟原来相似呢？

**Comment by greendreamer** [comment]
Currently, when converting pdf to docx, I get same result as pdf. Please check again.

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
