### ISSUE TITLE
转换docx表格中文本不全，请问这个可以解决吗

### ISSUE THREAD

**Issue by XuLei1992** [ArtifexSoftware/pdf2docx#293]
原始pdf如下图：
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/46668711/3a4c8b56-5420-4cfa-83d5-c6bc7968aeb3)
转换后的docx如下图：
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/46668711/02272cc4-c1fd-49bc-9137-f993f1c59126)

**Comment by greendreamer** [comment]
Closing this for lack of reaction for an extended amount of time.
Please check your pdf2docx version whether that is the latest or not.
Feel free to open a new issue - however please with a reproducing example.
