### ISSUE TITLE
含XFA表单域的PDF无法转换为word

### ISSUE THREAD

**Issue by HotSun6** [ArtifexSoftware/pdf2docx#300]
含XFA表单域的PDF转换为word的结果为：
Please wait... 
If this message is not eventually replaced by the proper contents of the document, your PDF viewer may not be able to display this type of document. 
You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by visiting  http://www.adobe.com/go/reader_download. 
For more assistance with Adobe Reader visit  http://www.adobe.com/go/acrreader. 
Windows is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries. Mac is a trademark of Apple Inc., registered in the United States and other countries. Linux is the registered trademark of Linus Torvalds in the U.S. and other countries.

**Comment by JorjMcKie** [comment]
No issue reported in this post.
