### ISSUE TITLE
pdf转word后，表格会溢出边界

### ISSUE THREAD

**Issue by mengyan258** [ArtifexSoftware/pdf2docx#302]
pdf转word后，表格会溢出边界

pdf 是
![微信截图_20240721171925](https://github.com/user-attachments/assets/8ac58dba-7097-4613-b6f4-0862fb7148d3)

转成的word是
![微信截图_20240721171811](https://github.com/user-attachments/assets/9eca6f53-ada6-40ae-bb9e-36f7ad2baec4)

**Comment by greendreamer** [comment]
Hi @mengyan258, Please share some examples to reproduce your bug.

**Comment by JorjMcKie** [comment]
Closing this for lack of reaction for an extended amount of time.
Feel free to open a new issue - however please with a reproducing example.
Please in that case use the new bug template and use English language only.
