### ISSUE TITLE
Hyperlinks are not transferred 

### ISSUE THREAD

**Issue by filiocorp** [ArtifexSoftware/pdf2docx#303]
Well, first off, thank you for the great library.  I have photos in my pdf that are hyperlinked, but when I transfer those, it does not transfer the hyperlink with those pictures in docx. Can you please help me if I am missing anything here?
@mzlogin @mzlogin @ChronosXYZ @dothinking

**Comment by JorjMcKie** [comment]
Please provide an example file!

**Comment by filiocorp** [comment]
This is a sample. The photo in the pdf is hyperlinked. 

-- Max
[Sample - photo with hyperlink.pdf](https://github.com/user-attachments/files/16606936/Sample.-.photo.with.hyperlink.pdf)

**Comment by filiocorp** [comment]
@JorjMcKie I'd appreciate your thoughts on this; or it something that I can do in the code to activate the images hyperlink? 
--Max

**Comment by JorjMcKie** [comment]
As of today, I have no idea how to do this.
It at all doable, it would be an enhancement request.
We will check out what options we may be able to open.

**Comment by filiocorp** [comment]
Is there any way I can help with this?

**Comment by greendreamer** [comment]
I think it is a little difficult to solve the issue. pdf2docx is using python-docx and the issue was not solved in python-docx yet.

**Comment by JorjMcKie** [comment]
@greendreamer thanks for digging this out!
