### ISSUE TITLE
没有正确换行

### ISSUE THREAD

**Issue by luocongqiu** [ArtifexSoftware/pdf2docx#317]
### Description of the bug

pdf文件内容：
<img width="947" alt="image" src="https://github.com/user-attachments/assets/e8741497-18d3-4086-a855-8de2c106d333">
转换后docx文件内容：
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/314e7b31-0c4b-4cf7-98ab-53eee48f3c70">

### How to reproduce the bug

无

### pdf2docx version

0.5.8

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment]
Please submit all issues in English language exclusively.
